namespace SVSim.Database.Enums;

public enum FeatureMaintenance
{
    ProfileMaintenance = 2001,
    MypageMaintenance,
    GiftMaintenance,
    SignupMaintenance,
    PaymentMaintenanceIOs,
    PaymentMaintenanceAndroid,
    PaymentMaintenanceDmm = 2025,
    PaymentMaintenanceSteam,
    ShopCardpackMaintenance = 2007,
    ShopBuilddeckMaintenance = 2032,
    ShopSleeveMaintenance = 2008,
    ShopSkinMaintenance = 2024,
    ShopItemMaintenance = 2037,
    AchievementMaintenance = 2009,
    MissionMaintenance,
    BpPointMaintenance,
    FreebattleMaintenance,
    RankbattleMaintenance,
    RoomBattleMaintenance,
    StoryMaintenance,
    PracticeMaintenance,
    ArenaTwopickMaintenance,
    CardMaintenance,
    DeckMaintenance,
    TutorialMaintenance,
    AccountMaintenance,
    FriendMaintenance,
    ArenaTwopickBattleMaintenance,
    RoomTwopickMaintenance = 2029,
    RoomAllMaintenance,
    RoomWatchingMaintenance,
    RoomRuleBo1 = 2038,
    RoomRuleTwoPick,
    RoomRuleTwoPickBackdraft,
    RoomRuleBo3,
    RoomRuleBo5,
    RoomRuleBo3Ban1 = 2071,
    RoomRuleBo5Ban1,
    ArenaConvention = 2043,
    FreebattleUnlimited,
    FreebattleRotation,
    RankbattleUnlimited,
    RankbattleRotation,
    RoomUnlimited,
    RoomRotation,
    Colosseum,
    ColosseumBattle,
    ColosseumRankMatchUser,
    RoomRuleTwoPickQube,
    GuildMaintenance,
    ArenaSealedMaintenance,
    ArenaSealedBattleMaintenance,
    RoomFormatHof,
    SealedDeckCode = 2059,
    SpotcardExchange,
    RoomPreRotation,
    RoomRuleTwoPickBo3,
    RoomRuleTwoPickBo5,
    FreebattlePrerotation = 2065,
    GatheringAll,
    GatheringCreate,
    BattlePass = 2070,
    RoomRuleTwoPickChaos = 2073,
    Quest = 2077,
    RoomFormatWindfall,
    DeckQrCode,
    AutoDeckCreate,
    CompetitionAll,
    CompetitionBattle,
    CompetitionRankMatchUser,
    FreebattleCrossover,
    RankbattleCrossover,
    RoomFormatCrossover,
    GatheringCrossover,
    PracticePuzzle,
    FreebattleMyrotation = 2093,
    RoomFormatMyrotation,
    GatheringMyrotation,
    BossRush,
    SecretBossBattle = 2100,
    ReplayAll = 2034,
    NewreplayAll = 2097,
    NewreplayExcludeRotation,
    NewreplayRecord,
    ChatGuild = 2101,
    ChatGathering,
    FreebattleAvatar,
    RoomFormatAvatar,
    GatheringAvatar,
    RoomRuleTwoPickCubeBackdraft,
    RoomRuleTwoPickCubeBo3,
    RoomRuleTwoPickCubeBo5,
    RoomRuleTwoPickChaosBackdraft,
    RoomRuleTwoPickChaosBo3,
    RoomRuleTwoPickChaosBo5,
    InvalidValue = 0
}