namespace Wizard;

public enum AIEmoteCmdType
{
	ON_FIRST_TURN,
	ON_ITERATION_START,
	ON_ALLY_TURN_START,
	ON_OPPONENT_TURN_START,
	ON_ALLY_TURN_END,
	ON_OPPONENT_TURN_END,
	ON_ALLY_ATTACK,
	ON_OPPONENT_ATTACK,
	ON_ALLY_EVOLUTION,
	ON_RECEIVE,
	ON_CARD_DESTROY,
	ON_CARD_PLAY_ALLY,
	ON_CARD_PLAY_OPPONENT,
	ON_DEBUG_SEARCH_ID,
	ON_DEBUG_SEARCH_CATEGORY,
	ON_LEADER_DAMAGED,
	ON_PLAYER_LEADER_DAMAGED
}
