namespace Wizard;

public enum eColorCodeId
{
	QuestBackButtonGradientTop,
	QuestBackButtonGradientBottom,
	QuestFooterOutline,
	QuestFooterGradientTop,
	QuestFooterGradientBottom,
	QuestSelectButtonTextColor,
	WIN_ORB_EFFECT_COLOR,
	LOSE_ORB_EFFECT_COLOR,
	DECISION_BTN_2_COLOR,
	CLASS_ELF_OUTLINE,
	CLASS_ROYAL_OUTLINE,
	CLASS_WITCH_OUTLINE,
	CLASS_DRAGON_OUTLINE,
	CLASS_NECROMANCER_OUTLINE,
	CLASS_VANPIRE_OUTLINE,
	CLASS_BISHOP_OUTLINE,
	CLASS_NEMESIS_OUTLINE,
	CLASS_SHADOW_OUTLINE,
	SEALED_CLASS_ELF_EFFECT_COLOR,
	SEALED_CLASS_ROYAL_EFFECT_COLOR,
	SEALED_CLASS_WITCH_EFFECT_COLOR,
	SEALED_CLASS_DRAGON_EFFECT_COLOR,
	SEALED_CLASS_NECRO_EFFECT_COLOR,
	SEALED_CLASS_VAMPIRE_EFFECT_COLOR,
	SEALED_CLASS_BISHOP_EFFECT_COLOR,
	SEALED_CLASS_NEMESIS_EFFECT_COLOR,
	MAX
}
