using System.Collections.Generic;

public class ApiType
{
	public enum Type
	{
		Load,
		GetCardMaster,
		Mypage,
		MypageFinishBattle,
		MypageRefresh,
		MyPageCodeInput,
		MyPageSettingUpdate,
		SpecialCrystalInfo,
		Profile,
		TutorialUpdate,
		TutorialUpdateAction,
		DownloadStart,
		DownloadFinish,
		CardDestruct,
		CardCreate,
		PremiumCardConversion,
		CardProtect,
		DeckInfo,
		OpenRoomDeckInfo,
		DeckMyList,
		DeckUpdate,
		DeckNameUpdate,
		DeckSet,
		EmptyDeckInfo,
		DeckOrder,
		DeckUpdateSleeve,
		DeckLeaderSkinUpdate,
		DeckRandomLeaderSkinUpdate,
		DeckIntroduction,
		IntroduceDeckSeries,
		DeckDelete,
		ConventionDeckDelete,
		PracticeDeckInfo,
		DeckAutoCreate,
		DeckUpdateConvention,
		DeckNameUpdateConvention,
		DeckUpdateSleeveConvention,
		DeckLeaderSkinUpdateConvention,
		DeckRandomLeaderSkinUpdateConvention,
		ConventionDeckOrder,
		ConventionDoWatch,
		ConventionInfo,
		ConventionRoomGetHistory,
		DeckInfoConvention,
		MainStoryInfo,
		MainStoryStart,
		MainStoryAllFinish,
		MainStoryFinish,
		MainStorySection,
		MainStoryLeaderSelect,
		MainStoryGetDeckList,
		LimitedStoryInfo,
		LimitedStoryStart,
		LimitedStoryAllFinish,
		LimitedStoryFinish,
		LimitedStorySection,
		LimitedStoryLeaderSelect,
		EventStorySection,
		EventStoryLeaderSelect,
		EventStoryInfo,
		EventStoryGetDeckList,
		EventStoryStart,
		EventStoryFinish,
		EventStoryAllFinish,
		AllStorySection,
		QuestInfo,
		QuestMission,
		QuestPoint,
		QuestStart,
		QuestFinish,
		QuestRewardReceive,
		QuestRewardReceiveAll,
		QuestGetDeckList,
		QuestPuzzleStart,
		QuestPuzzleFinish,
		QuestOpenPuzzleDialog,
		QuestTweet,
		FriendInfo,
		SendFriendApplyInfo,
		ReceiveFriendApplyInfo,
		FriendApplySend,
		FriendApplyApprove,
		FriendApplyCancel,
		FriendApplyCancelAll,
		FriendApplyReject,
		FriendApplyRejectAll,
		FriendReject,
		FriendUserSearch,
		PlayedTogetherInfo,
		GuildInfo,
		GuildCreate,
		GuildUpdate,
		GuildUpdateDescription,
		GuildEmblemList,
		GuildEmblemUpdate,
		GuildSearch,
		GuildOthersInfo,
		GuildJoin,
		GuildJoinRequestCancel,
		GuildJoinRequestList,
		GuildJoinRequestAccept,
		GuildJoinRequestReject,
		GuildInvite,
		GuildCancelInvite,
		GuildInviteUserList,
		GuildFriendList,
		GuildInvitedList,
		GuildRejectInvite,
		GuildChangeRole,
		GuildLeave,
		GuildBreakup,
		GuildRemove,
		GuildChatPost,
		GuildChatAddDeck,
		GuildChatAddReplay,
		GuildChatMessages,
		GuildChatDeckLog,
		GuildChatDeleteDeck,
		GuildChatReplayDetail,
		InformationTop,
		InformationDetail,
		MailTop,
		MailTopTutorial,
		MailRead,
		MailReadTutorial,
		RankMatchFinishRotation,
		RankMatchFinishUnlimited,
		RankMatchFinishCrossover,
		FreeMatchFinishRotation,
		FreeMatchFinishUnlimited,
		FreeMatchFinishPreRotation,
		FreeMatchFinishCrossover,
		FreeMatchFinishMyRotation,
		FreeMatchFinishAvatar,
		RankBattleDoMatchingRotation,
		RankBattleDoMatchingUnlimited,
		RankBattleDoMatchingCrossover,
		RankBattleFinishLoadRotation,
		RankBattleFinishLoadUnlimited,
		RankBattleForceFinish,
		FreeBattleDoMatchingRotation,
		FreeBattleDoMatchingUnlimited,
		FreeBattleDoMatchingPreRotation,
		FreeBattleDoMatchingCrossover,
		FreeBattleDoMatchingMyRotation,
		FreeBattleDoMatchingAvatar,
		FreeBattleFinishLoadRotation,
		FreeBattleFinishLoadUnlimited,
		FreeBattleFinishLoadAvatar,
		FreeBattleForceFinish,
		OpenRoomMatchFinish,
		OpenRoomBattleBattleDoMatching,
		OpenRoomBattleFinishLoad,
		OpenRoomBattleForceFinish,
		OpenRoom2PickMatchFinish,
		OpenRoomBattle2PickBattleDoMatching,
		EventRoomBattleBattleDoMatching,
		EventRoomBattleFinishLoad,
		BattleRecovery,
		BattleAbortRecovery,
		AbortSoloPlayRecovery,
		EventRoomMatchFinish,
		AIRotationRankBattleStart,
		AIRotationRankBattleFinish,
		AIUnlimitedRankBattleStart,
		AIUnlimitedRankBattleFinish,
		OpenRoomBattleCreateRoom,
		OpenRoomBattleCloseRoom,
		OpenRoomBattleKickRoom,
		OpenRoomBattleForceKickRoom,
		OpenRoomBattleSetDeck,
		OpenRoomBattleEnterRoom,
		OpenRoomBattleLeaveRoom,
		OpenRoomBattleWatch,
		OpenRoomInitializeRoomBattle,
		OpenRoomInitializeOwnerRoomRelations,
		OpenRoomDoWatch,
		OpenRoomForceClose,
		EventRoomBattleCreateRoom,
		EventRoomBattleEnterRoom,
		EventRoomBattleSetDeck,
		EventRoomInitializeRoomBattle,
		EventRoomBattleLeaveRoom,
		EventRoomBattleCloseRoom,
		EventRoomBattleKickRoom,
		EventRoomBattleForceKickRoom,
		EventRoomForceClose,
		EventRoomBattleWatch,
		OpenRoomGetRecoverParam,
		OpenRoomBattleBattleDoMatchingHOF,
		RoomAbortRecovery,
		RoomGetHashTag,
		OpenRoom2PickBattleDeckReset,
		OpenRoom2PickBattleBeginCreateDeck,
		OpenRoom2PickBattleSelectClass,
		OpenRoom2PickBattleSelectCard,
		OpenRoom2PickMultiBattleDeckReset,
		OpenRoom2PickMultiBattleBeginCreateDeck,
		OpenRoom2PickMultiBattleSelectClass,
		OpenRoom2PickMultiBattleSelectCard,
		OpenRoomBattle2PickMultiBattleDoMatching,
		OpenRoom2PickMultiBattleMatchFinish,
		OpenRoom2PickMultiBattleDeckList,
		OpenRoom2PickDraftBattleDeckReset,
		OpenRoom2PickDraftBattleBeginCreateDeck,
		OpenRoom2PickDraftBattleSelectClass,
		OpenRoom2PickDraftBattleSelectCard,
		OpenRoomBattle2PickDraftBattleDoMatching,
		OpenRoom2PickDraftMatchFinish,
		OpenRoomBattle2PickDraftFinishLoad,
		OpenRoom2PickCubeBattleDoMatching,
		OpenRoom2PickCubeBattleFinish,
		OpenRoom2PickCubeBattleResetDeck,
		OpenRoom2PickCubeBattleBeginCreateDeck,
		OpenRoom2PickCubeBattleSelectClass,
		OpenRoom2PickCubeBattleSelectCardSet,
		OpenRoom2PickCubeMultiBattleDoMatching,
		OpenRoom2PickCubeMultiBattleFinish,
		OpenRoom2PickCubeMultiBattleResetDeck,
		OpenRoom2PickCubeMultiBattleBeginCreateDeck,
		OpenRoom2PickCubeMultiBattleSelectClass,
		OpenRoom2PickCubeMultiBattleSelectCardSet,
		OpenRoom2PickCubeDraftBattleDeckReset,
		OpenRoom2PickCubeDraftBattleBeginCreateDeck,
		OpenRoom2PickCubeDraftBattleSelectClass,
		OpenRoom2PickCubeDraftBattleSelectCard,
		OpenRoomBattle2PickCubeDraftBattleDoMatching,
		OpenRoom2PickCubeDraftMatchFinish,
		OpenRoomBattle2PickCubeDraftFinishLoad,
		OpenRoom2PickChaosBattleDoMatching,
		OpenRoom2PickChaosBattleFinish,
		OpenRoom2PickChaosBattleResetDeck,
		OpenRoom2PickChaosBattleBeginCreateDeck,
		OpenRoom2PickChaosBattleSelectClass,
		OpenRoom2PickChaosBattleSelectCardSet,
		OpenRoom2PickChaosMultiBattleDoMatching,
		OpenRoom2PickChaosMultiBattleFinish,
		OpenRoom2PickChaosMultiBattleResetDeck,
		OpenRoom2PickChaosMultiBattleBeginCreateDeck,
		OpenRoom2PickChaosMultiBattleSelectClass,
		OpenRoom2PickChaosMultiBattleSelectCardSet,
		OpenRoom2PickChaosDraftBattleDeckReset,
		OpenRoom2PickChaosDraftBattleBeginCreateDeck,
		OpenRoom2PickChaosDraftBattleSelectClass,
		OpenRoom2PickChaosDraftBattleSelectCard,
		OpenRoomBattle2PickChaosDraftBattleDoMatching,
		OpenRoom2PickChaosDraftMatchFinish,
		OpenRoomBattle2PickChaosDraftFinishLoad,
		OpenRoomMultiDeckSet,
		OpenRoomMultiResetHistory,
		OpenRoomMultiGetHistory,
		EventRoomMultiDeckSet,
		EventRoomMultiResetHistory,
		OpenRoomMultiDeckBanDecideBan,
		OpenRoomGetDeckHof,
		OpenRoomSetDeckHof,
		OpenRoomMatchFinishHof,
		OpenRoomGetDeckAvatar,
		OpenRoomSetDeckAvatar,
		OpenRoomMatchFinishAvatar,
		OpenRoomBattleDoMatchingAvatar,
		GatheringRoomBattleSetDeck,
		GatheringRoomBattleDoMatching,
		GatheringRoomBattleFinish,
		GatheringRoomCreateRoom,
		GatheringRoomEnterRoom,
		GatheringRoomLeaveRoom,
		GatheringRoomLeaveRoomForTournament,
		GatheringRoomCloseRoom,
		GatheringRoomEnterVacancyRoom,
		GatheringRoomEnterRoomForTournament,
		GatheringRoomInitializeRoomBattle,
		GatheringRoomInitializeRoomBattleHistory,
		GatheringRoomKickRoom,
		GatheringRoomForceKickRoom,
		GatheringRoomForceKickRoomForTournament,
		GatheringRoomForceCloseRoom,
		GatheringRoomGetHistory,
		GatheringRoomDoWatch,
		GatheringRoomWatchRoom,
		GatheringRoomDeckEntry,
		ArenaTwoPickTop,
		ArenaTwoPickEntry,
		ArenaTwoPickClassCharaChoose,
		ArenaTwoPickCardChoose,
		ArenaTwoPickFinish,
		ArenaTwoPickRewardInfo,
		ArenaTwoPickRetire,
		ArenaTwoPickDoMatching,
		ArenaTwoPickFinishLoad,
		ArenaTwoPickFinishBattle,
		ArenaTwoPickChaosDoMatching,
		ArenaTwoPickChaosFinishBattle,
		ArenaTwoPickCubeDoMatching,
		ArenaTwoPickCubeFinishBattle,
		ArenaSealedTop,
		ArenaSealedEntry,
		ArenaSealedSelectClass,
		ArenaSealedGetCardPackInfo,
		ArenaSealedGetCardInfo,
		ArenaSealedUpdateDeck,
		ArenaSealedGetMaintCardList,
		ArenaSealedRetire,
		ArenaSealedFinish,
		ArenaSealedSelectPhantomCard,
		ArenaSealedBattleDoMatching,
		ArenaSealedBattleFinish,
		ChallangeHistory,
		ChallangeRankingHistory,
		ColosseumTop,
		ColosseumEntry,
		ColosseumEntryInfo,
		ColosseumDeckEntry,
		ColosseumDetail,
		ColosseumRetireNormalRound,
		ColosseumFinishAttachedReward,
		ColosseumTwoPickClassInit,
		ColosseumTwoPickClassSet,
		ColosseumTwoPickCardGet,
		ColosseumTwoPickCardSet,
		ColosseumHOFDeckInfo,
		ColosseumHOFDeckEntry,
		ColosseumWindFallDeckInfo,
		ColosseumWindFallDeckEntry,
		ColosseumAvatarDeckInfo,
		ColosseumAvatarDeckEntry,
		ColosseumDoMatching,
		ColosseumBattleFinishLoad,
		ColosseumBattleFinish,
		ColosseumDoMatchingRankMatch,
		ColosseumBattleFinishLoadRankMatch,
		ColosseumBattleFinishRankMatch,
		PackInfo,
		PackInfoTutorial,
		PackOpen,
		PackOpenTutorial,
		GetSelectSkinOwnedStatus,
		PackSetRotationStarterClass,
		GachaPointInfo,
		GachaPointExchange,
		BuildDeckInfo,
		BuildDeckBuy,
		BuildDeckGetPurchaseCount,
		SkinInfo,
		SkinBuySingle,
		SkinBuyMulti,
		SkinBuyMultiReward,
		SleeveInfo,
		SleeveBuy,
		SleeveList,
		SleeveFavorite,
		ItemPurchaseInfo,
		ItemPurchaseBuy,
		SpotCardInfo,
		SpotCardExchange,
		MissionInfo,
		MissionReceiveReward,
		MissionRetire,
		MissionBuyAdditionalRight,
		MissionChangeReceiveSetting,
		BeginnerMissionInfo,
		BeginnerMissionSendApply,
		AchievementReceiveReward,
		NameUpdate,
		RegionCodeUpdate,
		OfficialMarkDisplay,
		ConfigUpdate,
		ArenaConfigUpdate,
		ConfigUpdateFoilPreferred,
		ConfigUpdatePrizePreferred,
		DebugCacheClear,
		DebugPlusRupy,
		DebugPlusFrupy,
		DebugResetRupy,
		DebugResetFrupy,
		DebugUpdateCard,
		DebugUpdateCard1,
		DebugUpdateCard2,
		DebugResetCard,
		DebugResetSleeve,
		DebugReleaseClassChara,
		DebugAddBattlePoint,
		DebugTutorialUpdate,
		EmblemInfo,
		EmblemUpdate,
		EmblemFavorite,
		DegreeInfo,
		DegreeUpdate,
		DegreeFavorite,
		LeaderSkinInfo,
		LeaderSkinUpdate,
		RankingPeriodList,
		RankingRankMatchClassInfoRotation,
		RankingRankMatchClassInfoUnlimited,
		RankingRankMatchClassInfoCrossover,
		RankingMasterInfoRotation,
		RankingMasterInfoUnlimited,
		RankingMasterInfoCrossover,
		RankingTwoPickInfo,
		RankingSealedInfo,
		RankingMasterMyHistories,
		ItemAcquireHistoryInfo,
		PracticeInfo,
		PracticeStart,
		PracticeFinish,
		PracticePuzzleList,
		PracticePuzzleInfo,
		PracticePuzzleBattleStart,
		PracticePuzzleBattleFinish,
		PracticePuzzleMissionList,
		CountryCodeSet,
		SendAllTraceLog,
		SendTraceLog,
		SendLastTraceLog,
		GenerateDeckCode,
		GetDeckInfoFromDeckCode,
		GenerateDeckImage,
		GenerateDeckImageMaintenance,
		InviteGetFriendList,
		InviteFriend,
		InviteGetList,
		InviteCancel,
		InviteAccept,
		InviteConfigUpdate,
		ReplayInfo,
		ReplayDetail,
		GrandMaster,
		MasterResetMonth,
		BattleReport,
		Vote,
		VoteData,
		AcceptAgreement,
		CheckSpecialTitle,
		ClientCacheClear,
		DeleteUserData,
		LotteryInfo,
		LotteryReceive,
		LotteryReceiveDoubleChance,
		LotteryReceiveBigChance,
		LotteryReceiveTweetData,
		GatheringCreate,
		GatheringGetInfo,
		GatheringSelfInfo,
		GatheringEntry,
		GatheringLeave,
		GatheringInvite,
		GatheringInviteCancel,
		GatheringInviteReject,
		GatheringFriendList,
		GatheringInviteUserList,
		GatheringConfirmDeckList,
		GatheringDeckList,
		GatheringUpdateDeckName,
		GatheringUpdateDeckSleeve,
		GatheringUpdateDeckLeaderSkin,
		GatheringUpdateDeckRandomLeaderSkin,
		GatheringInterrupt,
		GatheringGetReceiveInvite,
		GatheringRanking,
		GatheringKick,
		GatheringUpdateDescription,
		GatheringInfoDependJoin,
		GatheringTournamentInfo,
		GatheringChatPost,
		GatheringChatMessages,
		GatheringChatAddDeck,
		GatheringChatAddReplay,
		GatheringChatReplayDetail,
		GatheringChatDeckLog,
		GatheringChatDeleteDeck,
		BattlePassInfo,
		BattlePassItemList,
		BattlePassBuy,
		AdjustSettingUpdate,
		OpenRoomGetDeckWindFall,
		OpenRoomSetDeckWindFall,
		OpenRoomMatchFinishWindFall,
		OpenRoomBattleBattleDoMatchingWindFall,
		CompetitionLobbyInfo,
		CompetitionRetire,
		CompetitionFinish,
		CompetitionBattleDoMatching,
		CompetitionBattleDoMatchingRankMatch,
		CompetitionBattleFinish,
		CompetitionBattleFinishRankMatch,
		CompetitionEntry,
		CompetitionRegisterDeck,
		CompetitionCheckPeriod,
		CompetitionJoin,
		CompetitionPermanentEntry,
		CompetitionClassChoose,
		CompetitionCardChoose,
		CompetitionSetCurrentDeck,
		BingoInfo,
		BingoDraw,
		BingoReceiveTweetData,
		CrossoverInfo,
		CrossoverReceiveRankReward,
		CrossoverReceiveAllRankRewards,
		CrossoverRankingMasterMyHistories,
		CrossoverGrandMaster,
		NeutralPopularityVoteInfo,
		NeutralPopularityVoteExecute,
		LeaderPopularityVoteInfo,
		LeaderPopularityVoteExecute,
		AccountDeleteReserve,
		AccountDeleteCancel,
		BossRushLobbyInfo,
		BossRushRegisterDeck,
		BossRushSetAbility,
		BossRushReceiveReward,
		BossRushRetire,
		BossRushStart,
		BossRushHiddenBattleStart,
		BossRushFinish,
		BossRushHiddenBattleFinish,
		BossRushLoseFinish,
		BossRushClearDeckList,
		ReceiveUpgradeTreasureBox,
		TreasureOpenSpecialTreasureBox,
		FreeCardPackBoxFinish,
		RedEtherCampaignLobby,
		TransitionInfo,
		TransitionPublish,
		TransitionDelete,
		CheckTimeSlipRotationPeriod
	}

	public static Dictionary<Type, string> ApiList = new Dictionary<Type, string>
	{
		{
			Type.Load,
			"load/index"
		},
		{
			Type.GetCardMaster,
			"immutable_data/card_master"
		},
		{
			Type.Mypage,
			"mypage/index"
		},
		{
			Type.MypageFinishBattle,
			"mypage/finish_battle"
		},
		{
			Type.MypageRefresh,
			"mypage/refresh"
		},
		{
			Type.MyPageCodeInput,
			"campaign/regist_serial_code"
		},
		{
			Type.MyPageSettingUpdate,
			"user_mypage/update"
		},
		{
			Type.SpecialCrystalInfo,
			"mypage/get_special_crystal_info"
		},
		{
			Type.Profile,
			"profile/index"
		},
		{
			Type.TutorialUpdate,
			"tutorial/update"
		},
		{
			Type.TutorialUpdateAction,
			"tutorial/update_action"
		},
		{
			Type.DownloadStart,
			"download_time/start"
		},
		{
			Type.DownloadFinish,
			"download_time/end"
		},
		{
			Type.CardDestruct,
			"card/destruct"
		},
		{
			Type.CardCreate,
			"card/create"
		},
		{
			Type.PremiumCardConversion,
			"card/create_foil_card"
		},
		{
			Type.CardProtect,
			"card/protect"
		},
		{
			Type.DeckInfo,
			"deck/info"
		},
		{
			Type.OpenRoomDeckInfo,
			"open_room/deck_list"
		},
		{
			Type.DeckMyList,
			"deck/my_list"
		},
		{
			Type.DeckUpdate,
			"deck/update"
		},
		{
			Type.DeckNameUpdate,
			"deck/update_name"
		},
		{
			Type.DeckSet,
			"deck/set_deck_redis"
		},
		{
			Type.EmptyDeckInfo,
			"deck/get_empty_deck_number"
		},
		{
			Type.DeckOrder,
			"deck/update_order"
		},
		{
			Type.DeckUpdateSleeve,
			"deck/update_sleeve"
		},
		{
			Type.DeckLeaderSkinUpdate,
			"deck/update_leader_skin"
		},
		{
			Type.DeckRandomLeaderSkinUpdate,
			"deck/update_random_leader_skin"
		},
		{
			Type.DeckIntroduction,
			"introduce_deck/info"
		},
		{
			Type.IntroduceDeckSeries,
			"introduce_deck/series_list"
		},
		{
			Type.DeckDelete,
			"deck/delete_deck_list"
		},
		{
			Type.PracticeDeckInfo,
			"practice/deck_list"
		},
		{
			Type.DeckAutoCreate,
			"auto_deck/create"
		},
		{
			Type.DeckInfoConvention,
			"offline_event/deck_info"
		},
		{
			Type.DeckUpdateConvention,
			"offline_event/deck_update"
		},
		{
			Type.DeckNameUpdateConvention,
			"offline_event/update_deck_name"
		},
		{
			Type.DeckUpdateSleeveConvention,
			"offline_event/update_sleeve"
		},
		{
			Type.DeckLeaderSkinUpdateConvention,
			"offline_event/update_leader_skin"
		},
		{
			Type.DeckRandomLeaderSkinUpdateConvention,
			"offline_event/update_random_leader_skin"
		},
		{
			Type.ConventionInfo,
			"offline_event/info"
		},
		{
			Type.ConventionRoomGetHistory,
			"open_room_offline_event/get_score"
		},
		{
			Type.ConventionDeckOrder,
			"offline_event/update_order"
		},
		{
			Type.ConventionDeckDelete,
			"offline_event/delete_deck_list"
		},
		{
			Type.ConventionDoWatch,
			"open_room_offline_event/do_watch"
		},
		{
			Type.MainStoryInfo,
			"main_story/info"
		},
		{
			Type.MainStoryStart,
			"main_story/start"
		},
		{
			Type.MainStoryFinish,
			"main_story/finish"
		},
		{
			Type.MainStoryAllFinish,
			"main_story/all_finish"
		},
		{
			Type.MainStorySection,
			"main_story/section"
		},
		{
			Type.MainStoryLeaderSelect,
			"main_story/leader_select"
		},
		{
			Type.MainStoryGetDeckList,
			"main_story/get_deck_list"
		},
		{
			Type.LimitedStoryInfo,
			"limited_story/info"
		},
		{
			Type.LimitedStoryStart,
			"limited_story/start"
		},
		{
			Type.LimitedStoryFinish,
			"limited_story/finish"
		},
		{
			Type.LimitedStoryAllFinish,
			"limited_story/all_finish"
		},
		{
			Type.LimitedStorySection,
			"limited_story/section"
		},
		{
			Type.LimitedStoryLeaderSelect,
			"limited_story/leader_select"
		},
		{
			Type.EventStorySection,
			"event_story/section"
		},
		{
			Type.EventStoryLeaderSelect,
			"event_story/leader_select"
		},
		{
			Type.EventStoryInfo,
			"event_story/info"
		},
		{
			Type.EventStoryGetDeckList,
			"event_story/get_deck_list"
		},
		{
			Type.EventStoryStart,
			"event_story/start"
		},
		{
			Type.EventStoryFinish,
			"event_story/finish"
		},
		{
			Type.EventStoryAllFinish,
			"event_story/all_finish"
		},
		{
			Type.AllStorySection,
			"story/section"
		},
		{
			Type.QuestInfo,
			"quest/info"
		},
		{
			Type.QuestMission,
			"quest/mission"
		},
		{
			Type.QuestPoint,
			"quest/point"
		},
		{
			Type.QuestStart,
			"quest/start"
		},
		{
			Type.QuestFinish,
			"quest/finish"
		},
		{
			Type.QuestRewardReceive,
			"quest/receive_reward"
		},
		{
			Type.QuestRewardReceiveAll,
			"quest/receive_reward_all"
		},
		{
			Type.QuestGetDeckList,
			"quest/get_deck_list"
		},
		{
			Type.QuestPuzzleStart,
			"quest/puzzle_start"
		},
		{
			Type.QuestPuzzleFinish,
			"quest/puzzle_finish"
		},
		{
			Type.QuestOpenPuzzleDialog,
			"quest/open_puzzle_dialog"
		},
		{
			Type.QuestTweet,
			"quest/receive_tweet_reward"
		},
		{
			Type.FriendInfo,
			"friend/info"
		},
		{
			Type.SendFriendApplyInfo,
			"friend/send_apply_info"
		},
		{
			Type.ReceiveFriendApplyInfo,
			"friend/receive_apply_info"
		},
		{
			Type.FriendApplySend,
			"friend/send_apply"
		},
		{
			Type.FriendApplyApprove,
			"friend/approve_apply"
		},
		{
			Type.FriendApplyCancel,
			"friend/cancel_apply"
		},
		{
			Type.FriendApplyCancelAll,
			"friend/cancel_apply_all"
		},
		{
			Type.FriendApplyReject,
			"friend/reject_apply"
		},
		{
			Type.FriendApplyRejectAll,
			"friend/reject_apply_all"
		},
		{
			Type.FriendReject,
			"friend/reject_friend"
		},
		{
			Type.FriendUserSearch,
			"friend/search_user"
		},
		{
			Type.PlayedTogetherInfo,
			"friend/played_together_info"
		},
		{
			Type.GuildInfo,
			"guild/info"
		},
		{
			Type.GuildCreate,
			"guild/create"
		},
		{
			Type.GuildUpdate,
			"guild/update"
		},
		{
			Type.GuildUpdateDescription,
			"guild/update_description"
		},
		{
			Type.GuildEmblemList,
			"guild/emblem_list"
		},
		{
			Type.GuildEmblemUpdate,
			"guild/update_emblem"
		},
		{
			Type.GuildSearch,
			"guild/search_guild"
		},
		{
			Type.GuildOthersInfo,
			"guild/others_info"
		},
		{
			Type.GuildJoin,
			"guild/join"
		},
		{
			Type.GuildJoinRequestCancel,
			"guild/cancel_join_request"
		},
		{
			Type.GuildJoinRequestList,
			"guild/join_request_list"
		},
		{
			Type.GuildJoinRequestAccept,
			"guild/join_request_accept"
		},
		{
			Type.GuildJoinRequestReject,
			"guild/reject_join_request"
		},
		{
			Type.GuildInvite,
			"guild/invite"
		},
		{
			Type.GuildCancelInvite,
			"guild/cancel_invite"
		},
		{
			Type.GuildInviteUserList,
			"guild/invite_user_list"
		},
		{
			Type.GuildFriendList,
			"guild/friend_list"
		},
		{
			Type.GuildInvitedList,
			"guild/invited_guild_list"
		},
		{
			Type.GuildRejectInvite,
			"guild/reject_invite"
		},
		{
			Type.GuildChangeRole,
			"guild/change_role"
		},
		{
			Type.GuildLeave,
			"guild/leave"
		},
		{
			Type.GuildBreakup,
			"guild/breakup"
		},
		{
			Type.GuildRemove,
			"guild/remove"
		},
		{
			Type.GuildChatPost,
			"guild_chat/post"
		},
		{
			Type.GuildChatAddDeck,
			"guild_chat/add_deck"
		},
		{
			Type.GuildChatAddReplay,
			"guild_chat/add_replay"
		},
		{
			Type.GuildChatMessages,
			"guild_chat/messages"
		},
		{
			Type.GuildChatDeckLog,
			"guild_chat/deck_log"
		},
		{
			Type.GuildChatDeleteDeck,
			"guild_chat/delete_deck"
		},
		{
			Type.GuildChatReplayDetail,
			"guild_chat/replay_detail"
		},
		{
			Type.InformationTop,
			"information/top"
		},
		{
			Type.InformationDetail,
			"information/detail/1"
		},
		{
			Type.MailTop,
			"gift/top"
		},
		{
			Type.MailTopTutorial,
			"tutorial/gift_top"
		},
		{
			Type.MailRead,
			"gift/receive_gift"
		},
		{
			Type.MailReadTutorial,
			"tutorial/gift_receive"
		},
		{
			Type.BattleRecovery,
			"battle/get_recovery_params"
		},
		{
			Type.BattleAbortRecovery,
			"battle/abort_recovery"
		},
		{
			Type.AbortSoloPlayRecovery,
			"npc_battle/abort_solo_play_recovery"
		},
		{
			Type.RankMatchFinishRotation,
			"rotation_rank_battle/finish"
		},
		{
			Type.RankMatchFinishUnlimited,
			"unlimited_rank_battle/finish"
		},
		{
			Type.RankMatchFinishCrossover,
			"crossover_rank_battle/finish"
		},
		{
			Type.RankBattleDoMatchingRotation,
			"rotation_rank_battle/do_matching"
		},
		{
			Type.RankBattleDoMatchingUnlimited,
			"unlimited_rank_battle/do_matching"
		},
		{
			Type.RankBattleDoMatchingCrossover,
			"crossover_rank_battle/do_matching"
		},
		{
			Type.RankBattleFinishLoadRotation,
			"rotation_rank_battle/finish_load"
		},
		{
			Type.RankBattleFinishLoadUnlimited,
			"unlimited_rank_battle/finish_load"
		},
		{
			Type.RankBattleForceFinish,
			"rank_battle/force_finish"
		},
		{
			Type.FreeBattleDoMatchingRotation,
			"rotation_free_battle/do_matching"
		},
		{
			Type.FreeBattleDoMatchingUnlimited,
			"unlimited_free_battle/do_matching"
		},
		{
			Type.FreeBattleDoMatchingPreRotation,
			"pre_rotation_free_battle/do_matching"
		},
		{
			Type.FreeBattleDoMatchingCrossover,
			"crossover_free_battle/do_matching"
		},
		{
			Type.FreeBattleDoMatchingMyRotation,
			"my_rotation_free_battle/do_matching"
		},
		{
			Type.FreeBattleDoMatchingAvatar,
			"avatar_free_battle/do_matching"
		},
		{
			Type.FreeBattleFinishLoadRotation,
			"rotation_free_battle/finish_load"
		},
		{
			Type.FreeBattleFinishLoadUnlimited,
			"unlimited_free_battle/finish_load"
		},
		{
			Type.FreeBattleFinishLoadAvatar,
			"avatar_free_battle/finish_load"
		},
		{
			Type.FreeMatchFinishRotation,
			"rotation_free_battle/finish"
		},
		{
			Type.FreeMatchFinishCrossover,
			"crossover_free_battle/finish"
		},
		{
			Type.FreeMatchFinishMyRotation,
			"my_rotation_free_battle/finish"
		},
		{
			Type.FreeMatchFinishAvatar,
			"avatar_free_battle/finish"
		},
		{
			Type.FreeMatchFinishUnlimited,
			"unlimited_free_battle/finish"
		},
		{
			Type.FreeMatchFinishPreRotation,
			"pre_rotation_free_battle/finish"
		},
		{
			Type.FreeBattleForceFinish,
			"free_battle/force_finish"
		},
		{
			Type.OpenRoomBattleBattleDoMatching,
			"open_room_battle/do_matching"
		},
		{
			Type.OpenRoomBattleBattleDoMatchingHOF,
			"open_room_hof_battle/do_matching"
		},
		{
			Type.OpenRoomBattleFinishLoad,
			"open_room_battle/finish_load"
		},
		{
			Type.OpenRoomMatchFinish,
			"open_room_battle/finish"
		},
		{
			Type.OpenRoomBattleForceFinish,
			"open_room_battle/force_finish"
		},
		{
			Type.EventRoomMatchFinish,
			"open_room_offline_event_battle/finish"
		},
		{
			Type.OpenRoomBattle2PickBattleDoMatching,
			"open_room_two_pick_battle/do_matching"
		},
		{
			Type.OpenRoom2PickMatchFinish,
			"open_room_two_pick_battle/finish"
		},
		{
			Type.EventRoomBattleBattleDoMatching,
			"open_room_offline_event_battle/do_matching"
		},
		{
			Type.EventRoomBattleFinishLoad,
			"open_room_offline_event_battle/finish_load"
		},
		{
			Type.AIRotationRankBattleStart,
			"ai_rotation_rank_battle/start"
		},
		{
			Type.AIRotationRankBattleFinish,
			"ai_rotation_rank_battle/finish"
		},
		{
			Type.AIUnlimitedRankBattleStart,
			"ai_unlimited_rank_battle/start"
		},
		{
			Type.AIUnlimitedRankBattleFinish,
			"ai_unlimited_rank_battle/finish"
		},
		{
			Type.OpenRoomBattleCreateRoom,
			"open_room/create_room"
		},
		{
			Type.OpenRoomBattleCloseRoom,
			"open_room/close_room"
		},
		{
			Type.OpenRoomBattleKickRoom,
			"open_room/kick_room"
		},
		{
			Type.OpenRoomBattleForceKickRoom,
			"open_room/force_kick_room"
		},
		{
			Type.OpenRoomBattleSetDeck,
			"open_room_battle/set_deck"
		},
		{
			Type.OpenRoomBattleEnterRoom,
			"open_room/enter_room"
		},
		{
			Type.OpenRoomBattleLeaveRoom,
			"open_room/leave_room"
		},
		{
			Type.OpenRoomBattleWatch,
			"open_room/watch_room"
		},
		{
			Type.OpenRoomInitializeRoomBattle,
			"open_room/initialize_room_battle"
		},
		{
			Type.OpenRoomDoWatch,
			"open_room/do_watch"
		},
		{
			Type.OpenRoomForceClose,
			"open_room/force_release_room"
		},
		{
			Type.OpenRoomGetRecoverParam,
			"open_room/get_recovery_params"
		},
		{
			Type.RoomAbortRecovery,
			"open_room/abort_recovery"
		},
		{
			Type.RoomGetHashTag,
			"open_room/get_hash_tags"
		},
		{
			Type.EventRoomBattleCreateRoom,
			"open_room_offline_event/create_room"
		},
		{
			Type.EventRoomBattleEnterRoom,
			"open_room_offline_event/enter_room"
		},
		{
			Type.EventRoomBattleSetDeck,
			"open_room_offline_event_battle/set_deck"
		},
		{
			Type.EventRoomInitializeRoomBattle,
			"open_room_offline_event/initialize_room_battle"
		},
		{
			Type.EventRoomBattleLeaveRoom,
			"open_room_offline_event/leave_room"
		},
		{
			Type.EventRoomBattleCloseRoom,
			"open_room_offline_event/close_room"
		},
		{
			Type.EventRoomBattleKickRoom,
			"open_room_offline_event/kick_room"
		},
		{
			Type.EventRoomBattleForceKickRoom,
			"open_room_offline_event/force_kick_room"
		},
		{
			Type.EventRoomForceClose,
			"open_room_offline_event/force_release_room"
		},
		{
			Type.EventRoomBattleWatch,
			"open_room_offline_event/watch_room"
		},
		{
			Type.OpenRoom2PickBattleDeckReset,
			"open_room_two_pick_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickBattleBeginCreateDeck,
			"open_room_two_pick_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickBattleSelectClass,
			"open_room_two_pick_battle/select_class"
		},
		{
			Type.OpenRoom2PickBattleSelectCard,
			"open_room_two_pick_battle/select_card_set"
		},
		{
			Type.OpenRoom2PickMultiBattleDeckReset,
			"open_room_two_pick_multiple_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickMultiBattleBeginCreateDeck,
			"open_room_two_pick_multiple_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickMultiBattleSelectClass,
			"open_room_two_pick_multiple_battle/select_class"
		},
		{
			Type.OpenRoom2PickMultiBattleSelectCard,
			"open_room_two_pick_multiple_battle/select_card_set"
		},
		{
			Type.OpenRoomBattle2PickMultiBattleDoMatching,
			"open_room_two_pick_multiple_battle/do_matching"
		},
		{
			Type.OpenRoom2PickMultiBattleMatchFinish,
			"open_room_two_pick_multiple_battle/finish"
		},
		{
			Type.OpenRoom2PickMultiBattleDeckList,
			"open_room_two_pick_multiple_battle/battle_result_list"
		},
		{
			Type.OpenRoomInitializeOwnerRoomRelations,
			"open_room/initialize_owner_room_relations"
		},
		{
			Type.OpenRoom2PickDraftBattleDeckReset,
			"open_room_two_pick_backdraft_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickDraftBattleBeginCreateDeck,
			"open_room_two_pick_backdraft_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickDraftBattleSelectClass,
			"open_room_two_pick_backdraft_battle/select_class"
		},
		{
			Type.OpenRoom2PickDraftBattleSelectCard,
			"open_room_two_pick_backdraft_battle/select_card_set"
		},
		{
			Type.OpenRoomBattle2PickDraftBattleDoMatching,
			"open_room_two_pick_backdraft_battle/do_matching"
		},
		{
			Type.OpenRoomBattle2PickDraftFinishLoad,
			"open_room_two_pick_backdraft_battle/finish_load"
		},
		{
			Type.OpenRoom2PickDraftMatchFinish,
			"open_room_two_pick_backdraft_battle/finish"
		},
		{
			Type.OpenRoom2PickCubeBattleDoMatching,
			"open_room_two_pick_cube_battle/do_matching"
		},
		{
			Type.OpenRoom2PickCubeBattleFinish,
			"open_room_two_pick_cube_battle/finish"
		},
		{
			Type.OpenRoom2PickCubeBattleResetDeck,
			"open_room_two_pick_cube_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickCubeBattleBeginCreateDeck,
			"open_room_two_pick_cube_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickCubeBattleSelectClass,
			"open_room_two_pick_cube_battle/select_class"
		},
		{
			Type.OpenRoom2PickCubeBattleSelectCardSet,
			"open_room_two_pick_cube_battle/select_card_set"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleDoMatching,
			"open_room_two_pick_cube_multiple_battle/do_matching"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleFinish,
			"open_room_two_pick_cube_multiple_battle/finish"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleResetDeck,
			"open_room_two_pick_cube_multiple_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleBeginCreateDeck,
			"open_room_two_pick_cube_multiple_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleSelectClass,
			"open_room_two_pick_cube_multiple_battle/select_class"
		},
		{
			Type.OpenRoom2PickCubeMultiBattleSelectCardSet,
			"open_room_two_pick_cube_multiple_battle/select_card_set"
		},
		{
			Type.OpenRoom2PickCubeDraftBattleDeckReset,
			"open_room_two_pick_cube_backdraft_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickCubeDraftBattleBeginCreateDeck,
			"open_room_two_pick_cube_backdraft_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickCubeDraftBattleSelectClass,
			"open_room_two_pick_cube_backdraft_battle/select_class"
		},
		{
			Type.OpenRoom2PickCubeDraftBattleSelectCard,
			"open_room_two_pick_cube_backdraft_battle/select_card_set"
		},
		{
			Type.OpenRoomBattle2PickCubeDraftBattleDoMatching,
			"open_room_two_pick_cube_backdraft_battle/do_matching"
		},
		{
			Type.OpenRoomBattle2PickCubeDraftFinishLoad,
			"open_room_two_pick_cube_backdraft_battle/finish_load"
		},
		{
			Type.OpenRoom2PickCubeDraftMatchFinish,
			"open_room_two_pick_cube_backdraft_battle/finish"
		},
		{
			Type.OpenRoom2PickChaosBattleDoMatching,
			"open_room_two_pick_chaos_battle/do_matching"
		},
		{
			Type.OpenRoom2PickChaosBattleFinish,
			"open_room_two_pick_chaos_battle/finish"
		},
		{
			Type.OpenRoom2PickChaosBattleResetDeck,
			"open_room_two_pick_chaos_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickChaosBattleBeginCreateDeck,
			"open_room_two_pick_chaos_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickChaosBattleSelectClass,
			"open_room_two_pick_chaos_battle/select_class"
		},
		{
			Type.OpenRoom2PickChaosBattleSelectCardSet,
			"open_room_two_pick_chaos_battle/select_card_set"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleDoMatching,
			"open_room_two_pick_chaos_multiple_battle/do_matching"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleFinish,
			"open_room_two_pick_chaos_multiple_battle/finish"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleResetDeck,
			"open_room_two_pick_chaos_multiple_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleBeginCreateDeck,
			"open_room_two_pick_chaos_multiple_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleSelectClass,
			"open_room_two_pick_chaos_multiple_battle/select_class"
		},
		{
			Type.OpenRoom2PickChaosMultiBattleSelectCardSet,
			"open_room_two_pick_chaos_multiple_battle/select_card_set"
		},
		{
			Type.OpenRoom2PickChaosDraftBattleDeckReset,
			"open_room_two_pick_chaos_backdraft_battle/reset_deck"
		},
		{
			Type.OpenRoom2PickChaosDraftBattleBeginCreateDeck,
			"open_room_two_pick_chaos_backdraft_battle/begin_create_deck"
		},
		{
			Type.OpenRoom2PickChaosDraftBattleSelectClass,
			"open_room_two_pick_chaos_backdraft_battle/select_class"
		},
		{
			Type.OpenRoom2PickChaosDraftBattleSelectCard,
			"open_room_two_pick_chaos_backdraft_battle/select_card_set"
		},
		{
			Type.OpenRoomBattle2PickChaosDraftBattleDoMatching,
			"open_room_two_pick_chaos_backdraft_battle/do_matching"
		},
		{
			Type.OpenRoomBattle2PickChaosDraftFinishLoad,
			"open_room_two_pick_chaos_backdraft_battle/finish_load"
		},
		{
			Type.OpenRoom2PickChaosDraftMatchFinish,
			"open_room_two_pick_chaos_backdraft_battle/finish"
		},
		{
			Type.OpenRoomMultiDeckSet,
			"deck/deck_entry"
		},
		{
			Type.OpenRoomMultiResetHistory,
			"open_room/initialize_room_battle_history"
		},
		{
			Type.OpenRoomMultiGetHistory,
			"open_room/get_score"
		},
		{
			Type.EventRoomMultiDeckSet,
			"offline_event/deck_entry"
		},
		{
			Type.EventRoomMultiResetHistory,
			"open_room_offline_event/initialize_room_battle_history"
		},
		{
			Type.OpenRoomMultiDeckBanDecideBan,
			"open_room/ban_deck"
		},
		{
			Type.OpenRoomGetDeckHof,
			"open_room_hof_battle/get_hof_deck_list"
		},
		{
			Type.OpenRoomSetDeckHof,
			"open_room_hof_battle/set_deck"
		},
		{
			Type.OpenRoomMatchFinishHof,
			"open_room_hof_battle/finish"
		},
		{
			Type.OpenRoomGetDeckWindFall,
			"open_room_windfall_battle/get_windfall_deck_list"
		},
		{
			Type.OpenRoomSetDeckWindFall,
			"open_room_windfall_battle/set_deck"
		},
		{
			Type.OpenRoomMatchFinishWindFall,
			"open_room_windfall_battle/finish"
		},
		{
			Type.OpenRoomBattleBattleDoMatchingWindFall,
			"open_room_windfall_battle/do_matching"
		},
		{
			Type.OpenRoomGetDeckAvatar,
			"open_room_avatar_battle/get_avatar_deck_list"
		},
		{
			Type.OpenRoomSetDeckAvatar,
			"open_room_avatar_battle/set_deck"
		},
		{
			Type.OpenRoomMatchFinishAvatar,
			"open_room_avatar_battle/finish"
		},
		{
			Type.OpenRoomBattleDoMatchingAvatar,
			"open_room_avatar_battle/do_matching"
		},
		{
			Type.GatheringRoomBattleSetDeck,
			"gathering_room_battle/set_deck"
		},
		{
			Type.GatheringRoomBattleDoMatching,
			"gathering_room_battle/do_matching"
		},
		{
			Type.GatheringRoomBattleFinish,
			"gathering_room_battle/finish"
		},
		{
			Type.GatheringRoomCreateRoom,
			"gathering_room/create_room"
		},
		{
			Type.GatheringRoomEnterRoom,
			"gathering_room/enter_room"
		},
		{
			Type.GatheringRoomLeaveRoom,
			"gathering_room/leave_room"
		},
		{
			Type.GatheringRoomLeaveRoomForTournament,
			"gathering_room/leave_room_for_tournament"
		},
		{
			Type.GatheringRoomCloseRoom,
			"gathering_room/close_room"
		},
		{
			Type.GatheringRoomEnterVacancyRoom,
			"gathering_room/enter_vacancy_room"
		},
		{
			Type.GatheringRoomEnterRoomForTournament,
			"gathering_room/enter_room_for_tournament"
		},
		{
			Type.GatheringRoomInitializeRoomBattle,
			"gathering_room/initialize_room_battle"
		},
		{
			Type.GatheringRoomInitializeRoomBattleHistory,
			"gathering_room/initialize_room_battle_history"
		},
		{
			Type.GatheringRoomKickRoom,
			"gathering_room/kick_room"
		},
		{
			Type.GatheringRoomForceKickRoom,
			"gathering_room/force_kick_room"
		},
		{
			Type.GatheringRoomForceKickRoomForTournament,
			"gathering_room/force_kick_room_for_tournament"
		},
		{
			Type.GatheringRoomForceCloseRoom,
			"gathering_room/force_release_room"
		},
		{
			Type.GatheringRoomGetHistory,
			"gathering_room/get_score"
		},
		{
			Type.GatheringRoomDoWatch,
			"gathering_room/do_watch"
		},
		{
			Type.GatheringRoomWatchRoom,
			"gathering_room/watch_room"
		},
		{
			Type.GatheringRoomDeckEntry,
			"gathering_room/deck_entry"
		},
		{
			Type.ArenaTwoPickTop,
			"arena_two_pick/top"
		},
		{
			Type.ArenaTwoPickEntry,
			"arena_two_pick/entry"
		},
		{
			Type.ArenaTwoPickClassCharaChoose,
			"arena_two_pick/class_choose"
		},
		{
			Type.ArenaTwoPickCardChoose,
			"arena_two_pick/card_choose"
		},
		{
			Type.ArenaTwoPickFinish,
			"arena_two_pick/finish"
		},
		{
			Type.ArenaTwoPickRewardInfo,
			"arena_two_pick/reward_info"
		},
		{
			Type.ArenaTwoPickRetire,
			"arena_two_pick/retire"
		},
		{
			Type.ArenaTwoPickDoMatching,
			"arena_two_pick_battle/do_matching"
		},
		{
			Type.ArenaTwoPickFinishLoad,
			"arena_two_pick_battle/finish_load"
		},
		{
			Type.ArenaTwoPickFinishBattle,
			"arena_two_pick_battle/finish"
		},
		{
			Type.ArenaTwoPickChaosDoMatching,
			"arena_two_pick_chaos_battle/do_matching"
		},
		{
			Type.ArenaTwoPickChaosFinishBattle,
			"arena_two_pick_chaos_battle/finish"
		},
		{
			Type.ArenaTwoPickCubeDoMatching,
			"arena_two_pick_cube_battle/do_matching"
		},
		{
			Type.ArenaTwoPickCubeFinishBattle,
			"arena_two_pick_cube_battle/finish"
		},
		{
			Type.ArenaSealedTop,
			"arena_sealed/top"
		},
		{
			Type.ArenaSealedEntry,
			"arena_sealed/entry"
		},
		{
			Type.ArenaSealedSelectClass,
			"arena_sealed/select_class"
		},
		{
			Type.ArenaSealedGetCardPackInfo,
			"arena_sealed/pack_info"
		},
		{
			Type.ArenaSealedGetCardInfo,
			"arena_sealed/get_card_list"
		},
		{
			Type.ArenaSealedUpdateDeck,
			"arena_sealed/update_deck"
		},
		{
			Type.ArenaSealedGetMaintCardList,
			"arena_sealed/get_card_maintenance_list"
		},
		{
			Type.ArenaSealedRetire,
			"arena_sealed/retire"
		},
		{
			Type.ArenaSealedFinish,
			"arena_sealed/finish"
		},
		{
			Type.ArenaSealedSelectPhantomCard,
			"arena_sealed/select_phantom_card"
		},
		{
			Type.ArenaSealedBattleDoMatching,
			"arena_sealed_battle/do_matching"
		},
		{
			Type.ArenaSealedBattleFinish,
			"arena_sealed_battle/finish"
		},
		{
			Type.ChallangeHistory,
			"arena/get_challenge_info"
		},
		{
			Type.ChallangeRankingHistory,
			"arena/get_challenge_ranking_history"
		},
		{
			Type.ColosseumTop,
			"arena_colosseum/top"
		},
		{
			Type.ColosseumEntry,
			"arena_colosseum/entry"
		},
		{
			Type.ColosseumEntryInfo,
			"arena_colosseum/get_fee_info"
		},
		{
			Type.ColosseumDeckEntry,
			"arena_colosseum/register_deck"
		},
		{
			Type.ColosseumDetail,
			"arena_colosseum/event_info"
		},
		{
			Type.ColosseumRetireNormalRound,
			"arena_colosseum/retire"
		},
		{
			Type.ColosseumFinishAttachedReward,
			"arena_colosseum/finish"
		},
		{
			Type.ColosseumTwoPickClassInit,
			"arena_colosseum/get_candidate_classes"
		},
		{
			Type.ColosseumTwoPickClassSet,
			"arena_colosseum/class_choose"
		},
		{
			Type.ColosseumTwoPickCardGet,
			"arena_colosseum/get_candidate_cards"
		},
		{
			Type.ColosseumTwoPickCardSet,
			"arena_colosseum/card_choose"
		},
		{
			Type.ColosseumHOFDeckInfo,
			"arena_colosseum/get_hof_deck_list"
		},
		{
			Type.ColosseumHOFDeckEntry,
			"arena_colosseum/register_hof_deck"
		},
		{
			Type.ColosseumWindFallDeckInfo,
			"arena_colosseum/get_windfall_deck_list"
		},
		{
			Type.ColosseumWindFallDeckEntry,
			"arena_colosseum/register_windfall_deck"
		},
		{
			Type.ColosseumAvatarDeckInfo,
			"arena_colosseum/get_avatar_deck_list"
		},
		{
			Type.ColosseumAvatarDeckEntry,
			"arena_colosseum/register_avatar_deck"
		},
		{
			Type.ColosseumDoMatching,
			"colosseum_battle/do_matching"
		},
		{
			Type.ColosseumBattleFinishLoad,
			"colosseum_battle/finish_load"
		},
		{
			Type.ColosseumBattleFinish,
			"colosseum_battle/finish"
		},
		{
			Type.ColosseumDoMatchingRankMatch,
			"colosseum_rank_battle/do_matching"
		},
		{
			Type.ColosseumBattleFinishLoadRankMatch,
			"colosseum_rank_battle/finish_load"
		},
		{
			Type.ColosseumBattleFinishRankMatch,
			"colosseum_rank_battle/finish"
		},
		{
			Type.PackInfo,
			"pack/info"
		},
		{
			Type.PackInfoTutorial,
			"tutorial/pack_info"
		},
		{
			Type.PackOpen,
			"pack/open"
		},
		{
			Type.PackOpenTutorial,
			"tutorial/pack_open"
		},
		{
			Type.GetSelectSkinOwnedStatus,
			"pack/get_leader_skin_owned_status"
		},
		{
			Type.PackSetRotationStarterClass,
			"pack/set_rotation_starter_class"
		},
		{
			Type.GachaPointInfo,
			"pack/get_gacha_point_rewards"
		},
		{
			Type.GachaPointExchange,
			"pack/exchange_gacha_point"
		},
		{
			Type.BuildDeckInfo,
			"build_deck/info"
		},
		{
			Type.BuildDeckBuy,
			"build_deck/buy"
		},
		{
			Type.BuildDeckGetPurchaseCount,
			"build_deck/get_purchase_count"
		},
		{
			Type.SkinInfo,
			"leader_skin/products"
		},
		{
			Type.SkinBuySingle,
			"leader_skin/buy"
		},
		{
			Type.SkinBuyMulti,
			"leader_skin/buy_set"
		},
		{
			Type.SkinBuyMultiReward,
			"leader_skin/buy_set_item"
		},
		{
			Type.SleeveInfo,
			"sleeve/info"
		},
		{
			Type.SleeveBuy,
			"sleeve/buy"
		},
		{
			Type.SleeveList,
			"sleeve/sleeve_list"
		},
		{
			Type.SleeveFavorite,
			"sleeve/favorite"
		},
		{
			Type.ItemPurchaseInfo,
			"item_purchase/info"
		},
		{
			Type.ItemPurchaseBuy,
			"item_purchase/purchase"
		},
		{
			Type.SpotCardInfo,
			"spot_card_exchange/top"
		},
		{
			Type.SpotCardExchange,
			"spot_card_exchange/exchange"
		},
		{
			Type.MissionInfo,
			"mission/info"
		},
		{
			Type.MissionReceiveReward,
			"mission/receive_reward"
		},
		{
			Type.MissionRetire,
			"mission/retire"
		},
		{
			Type.MissionBuyAdditionalRight,
			"mission/buy_additional_right"
		},
		{
			Type.MissionChangeReceiveSetting,
			"mission/change_receive_setting"
		},
		{
			Type.BeginnerMissionInfo,
			"beginner_mission/info"
		},
		{
			Type.BeginnerMissionSendApply,
			"beginner_mission/send_apply"
		},
		{
			Type.AchievementReceiveReward,
			"achievement/receive_reward"
		},
		{
			Type.NameUpdate,
			"account/update_name"
		},
		{
			Type.RegionCodeUpdate,
			"account/update_region_code"
		},
		{
			Type.OfficialMarkDisplay,
			"profile/update_official_mark_display"
		},
		{
			Type.ConfigUpdate,
			"config/update"
		},
		{
			Type.ArenaConfigUpdate,
			"config/update_challenge_config"
		},
		{
			Type.ConfigUpdateFoilPreferred,
			"config/update_foil_preferred"
		},
		{
			Type.ConfigUpdatePrizePreferred,
			"config/update_prize_preferred"
		},
		{
			Type.DebugCacheClear,
			"debug/memcache_flush"
		},
		{
			Type.DebugPlusRupy,
			"debug/plus_rupy"
		},
		{
			Type.DebugPlusFrupy,
			"debug/plus_frupy"
		},
		{
			Type.DebugResetRupy,
			"debug/reset_rupy"
		},
		{
			Type.DebugResetFrupy,
			"debug/reset_frupy"
		},
		{
			Type.DebugUpdateCard,
			"debug/update_card"
		},
		{
			Type.DebugUpdateCard1,
			"debug/update_card_1"
		},
		{
			Type.DebugUpdateCard2,
			"debug/update_card_2"
		},
		{
			Type.DebugResetCard,
			"debug/reset_card"
		},
		{
			Type.DebugResetSleeve,
			"debug/reset_sleeve"
		},
		{
			Type.DebugReleaseClassChara,
			"debug/release_class_chara"
		},
		{
			Type.DebugAddBattlePoint,
			"rank_match/add_battle_point"
		},
		{
			Type.DebugTutorialUpdate,
			"tutorial/debug_update"
		},
		{
			Type.EmblemInfo,
			"emblem/emblem_list"
		},
		{
			Type.EmblemUpdate,
			"emblem/update_emblem"
		},
		{
			Type.EmblemFavorite,
			"emblem/favorite"
		},
		{
			Type.DegreeInfo,
			"degree/degree_list"
		},
		{
			Type.DegreeUpdate,
			"degree/update_degree"
		},
		{
			Type.DegreeFavorite,
			"degree/favorite"
		},
		{
			Type.LeaderSkinInfo,
			"leader_skin/ids"
		},
		{
			Type.LeaderSkinUpdate,
			"leader_skin/set"
		},
		{
			Type.RankingPeriodList,
			"ranking/get_viewable_ranking_period_list"
		},
		{
			Type.RankingRankMatchClassInfoRotation,
			"ranking/rank_match_class_win_rotation_info"
		},
		{
			Type.RankingRankMatchClassInfoUnlimited,
			"ranking/rank_match_class_win_unlimited_info"
		},
		{
			Type.RankingRankMatchClassInfoCrossover,
			"ranking/rank_match_class_win_crossover_info"
		},
		{
			Type.RankingMasterInfoRotation,
			"ranking/master_point_rotation_info"
		},
		{
			Type.RankingMasterInfoUnlimited,
			"ranking/master_point_unlimited_info"
		},
		{
			Type.RankingMasterInfoCrossover,
			"ranking/master_point_crossover_info"
		},
		{
			Type.RankingTwoPickInfo,
			"ranking/two_pick_win_info"
		},
		{
			Type.RankingSealedInfo,
			"ranking/sealed_all_win_info"
		},
		{
			Type.RankingMasterMyHistories,
			"ranking/my_master_point_histories"
		},
		{
			Type.ItemAcquireHistoryInfo,
			"item_acquire_history/info"
		},
		{
			Type.PracticeInfo,
			"practice/info"
		},
		{
			Type.PracticeStart,
			"practice/start"
		},
		{
			Type.PracticeFinish,
			"practice/finish"
		},
		{
			Type.PracticePuzzleList,
			"basic_puzzle/open_puzzle_dialog"
		},
		{
			Type.PracticePuzzleInfo,
			"basic_puzzle/info"
		},
		{
			Type.PracticePuzzleBattleStart,
			"basic_puzzle/start"
		},
		{
			Type.PracticePuzzleBattleFinish,
			"basic_puzzle/finish"
		},
		{
			Type.PracticePuzzleMissionList,
			"basic_puzzle/mission"
		},
		{
			Type.CountryCodeSet,
			"config/update_country_code"
		},
		{
			Type.SendAllTraceLog,
			"rank_battle/add_all_client_log"
		},
		{
			Type.SendTraceLog,
			"rank_battle/add_client_log"
		},
		{
			Type.SendLastTraceLog,
			"rank_battle/add_last_turn_log"
		},
		{
			Type.GetDeckInfoFromDeckCode,
			"deck?format=msgpack"
		},
		{
			Type.GenerateDeckCode,
			"deck_code?format=msgpack"
		},
		{
			Type.GenerateDeckImage,
			"deck_image?lang={0}&format=msgpack"
		},
		{
			Type.GenerateDeckImageMaintenance,
			"deck/image"
		},
		{
			Type.InviteGetFriendList,
			"friend_battle/friend_list"
		},
		{
			Type.InviteFriend,
			"friend_battle/invite"
		},
		{
			Type.InviteGetList,
			"friend_battle/invitation_list"
		},
		{
			Type.InviteCancel,
			"friend_battle/cancel"
		},
		{
			Type.InviteAccept,
			"friend_battle/accept"
		},
		{
			Type.InviteConfigUpdate,
			"config/update_config"
		},
		{
			Type.ReplayInfo,
			"replay/info"
		},
		{
			Type.ReplayDetail,
			"replay/detail"
		},
		{
			Type.GrandMaster,
			"profile/get_grand_master_data"
		},
		{
			Type.MasterResetMonth,
			"rank_battle/get_latest_master_point"
		},
		{
			Type.BattleReport,
			"report/battle_report"
		},
		{
			Type.Vote,
			"vote/execute"
		},
		{
			Type.VoteData,
			"vote/info"
		},
		{
			Type.AcceptAgreement,
			"check/accept_agreement"
		},
		{
			Type.CheckSpecialTitle,
			"check/special_title"
		},
		{
			Type.ClientCacheClear,
			"npc_battle/client_cache_clear"
		},
		{
			Type.DeleteUserData,
			"account/delete_user_data"
		},
		{
			Type.LotteryInfo,
			"lottery/info"
		},
		{
			Type.LotteryReceive,
			"lottery/Receive"
		},
		{
			Type.LotteryReceiveDoubleChance,
			"lottery/receive_double_chance"
		},
		{
			Type.LotteryReceiveBigChance,
			"lottery/receive_big_chance"
		},
		{
			Type.LotteryReceiveTweetData,
			"lottery/receive_tweet_reward"
		},
		{
			Type.GatheringCreate,
			"gathering/create"
		},
		{
			Type.GatheringGetInfo,
			"gathering/search"
		},
		{
			Type.GatheringEntry,
			"gathering/join"
		},
		{
			Type.GatheringLeave,
			"gathering/leave"
		},
		{
			Type.GatheringSelfInfo,
			"gathering/info"
		},
		{
			Type.GatheringInvite,
			"gathering/send_invite"
		},
		{
			Type.GatheringInviteCancel,
			"gathering/cancel_invite"
		},
		{
			Type.GatheringInviteReject,
			"gathering/reject_invite"
		},
		{
			Type.GatheringFriendList,
			"gathering/friend_list"
		},
		{
			Type.GatheringInviteUserList,
			"gathering/send_invite_list"
		},
		{
			Type.GatheringConfirmDeckList,
			"gathering/confirm_deck_list"
		},
		{
			Type.GatheringDeckList,
			"gathering/deck_list"
		},
		{
			Type.GatheringUpdateDeckName,
			"gathering/update_deck_name"
		},
		{
			Type.GatheringUpdateDeckSleeve,
			"gathering/update_deck_sleeve"
		},
		{
			Type.GatheringUpdateDeckLeaderSkin,
			"gathering/update_deck_leader_skin"
		},
		{
			Type.GatheringUpdateDeckRandomLeaderSkin,
			"gathering/update_deck_random_leader_skin"
		},
		{
			Type.GatheringInterrupt,
			"gathering/interrupt"
		},
		{
			Type.GatheringGetReceiveInvite,
			"gathering/receive_invite_list"
		},
		{
			Type.GatheringRanking,
			"gathering/ranking"
		},
		{
			Type.GatheringKick,
			"gathering/kick_member"
		},
		{
			Type.GatheringUpdateDescription,
			"gathering/update_description"
		},
		{
			Type.GatheringInfoDependJoin,
			"gathering/refresh"
		},
		{
			Type.GatheringTournamentInfo,
			"gathering/tournament_info"
		},
		{
			Type.GatheringChatPost,
			"gathering_chat/post"
		},
		{
			Type.GatheringChatMessages,
			"gathering_chat/messages"
		},
		{
			Type.GatheringChatAddDeck,
			"gathering_chat/add_deck"
		},
		{
			Type.GatheringChatAddReplay,
			"gathering_chat/add_replay"
		},
		{
			Type.GatheringChatReplayDetail,
			"gathering_chat/replay_detail"
		},
		{
			Type.GatheringChatDeckLog,
			"gathering_chat/deck_log"
		},
		{
			Type.GatheringChatDeleteDeck,
			"gathering_chat/delete_deck"
		},
		{
			Type.BattlePassInfo,
			"battle_pass/info"
		},
		{
			Type.BattlePassItemList,
			"battle_pass/item_list"
		},
		{
			Type.BattlePassBuy,
			"battle_pass/buy"
		},
		{
			Type.AdjustSettingUpdate,
			"adjust/update_adjust_config"
		},
		{
			Type.CompetitionLobbyInfo,
			"arena_competition/top"
		},
		{
			Type.CompetitionRetire,
			"arena_competition/retire"
		},
		{
			Type.CompetitionFinish,
			"arena_competition/finish"
		},
		{
			Type.CompetitionBattleDoMatching,
			"competition_battle/do_matching"
		},
		{
			Type.CompetitionBattleDoMatchingRankMatch,
			"competition_rank_battle/do_matching"
		},
		{
			Type.CompetitionBattleFinish,
			"competition_battle/finish"
		},
		{
			Type.CompetitionBattleFinishRankMatch,
			"competition_rank_battle/finish"
		},
		{
			Type.CompetitionEntry,
			"arena_competition/entry"
		},
		{
			Type.CompetitionRegisterDeck,
			"arena_competition/register_deck"
		},
		{
			Type.CompetitionCheckPeriod,
			"arena_competition/check_schedule"
		},
		{
			Type.CompetitionJoin,
			"arena_competition/join"
		},
		{
			Type.CompetitionPermanentEntry,
			"arena_competition/permanent_entry"
		},
		{
			Type.CompetitionClassChoose,
			"arena_competition/class_choose"
		},
		{
			Type.CompetitionCardChoose,
			"arena_competition/card_choose"
		},
		{
			Type.CompetitionSetCurrentDeck,
			"arena_competition/set_current_deck_no"
		},
		{
			Type.BingoInfo,
			"bingo/info"
		},
		{
			Type.BingoDraw,
			"bingo/draw"
		},
		{
			Type.BingoReceiveTweetData,
			"bingo/receive_tweet_reward"
		},
		{
			Type.CrossoverInfo,
			"crossover/info"
		},
		{
			Type.CrossoverReceiveRankReward,
			"crossover/receive_rank_reward"
		},
		{
			Type.CrossoverReceiveAllRankRewards,
			"crossover/receive_all_rank_rewards"
		},
		{
			Type.CrossoverRankingMasterMyHistories,
			"crossover/my_master_point_histories"
		},
		{
			Type.CrossoverGrandMaster,
			"crossover/get_grand_master_data"
		},
		{
			Type.NeutralPopularityVoteInfo,
			"card_vote/info"
		},
		{
			Type.NeutralPopularityVoteExecute,
			"card_vote/vote"
		},
		{
			Type.LeaderPopularityVoteInfo,
			"leader_skin_vote/info"
		},
		{
			Type.LeaderPopularityVoteExecute,
			"leader_skin_vote/vote"
		},
		{
			Type.AccountDeleteReserve,
			"account_delete_reservation/reserve"
		},
		{
			Type.AccountDeleteCancel,
			"account_delete_reservation/cancel"
		},
		{
			Type.BossRushLobbyInfo,
			"bossrush/base"
		},
		{
			Type.BossRushRegisterDeck,
			"bossrush/register_deck"
		},
		{
			Type.BossRushSetAbility,
			"bossrush/set_ability"
		},
		{
			Type.BossRushReceiveReward,
			"bossrush/receive_reward"
		},
		{
			Type.BossRushRetire,
			"bossrush/retire"
		},
		{
			Type.BossRushStart,
			"bossrush/start"
		},
		{
			Type.BossRushHiddenBattleStart,
			"bossrush/start_hidden_boss_battle"
		},
		{
			Type.BossRushFinish,
			"bossrush/finish"
		},
		{
			Type.BossRushHiddenBattleFinish,
			"bossrush/finish_hidden_boss_battle"
		},
		{
			Type.BossRushLoseFinish,
			"bossrush/lose_finish_challange"
		},
		{
			Type.BossRushClearDeckList,
			"bossrush/clear_deck_info"
		},
		{
			Type.ReceiveUpgradeTreasureBox,
			"upgrade_treasure_box_campaign/receive_upgrade_treasure_box"
		},
		{
			Type.TreasureOpenSpecialTreasureBox,
			"treasure/open_special_treasure"
		},
		{
			Type.FreeCardPackBoxFinish,
			"free_card_pack_box_campaign/finish"
		},
		{
			Type.RedEtherCampaignLobby,
			"red_ether_campaign/info"
		},
		{
			Type.TransitionInfo,
			"account/get_account_transition_status_with_two"
		},
		{
			Type.TransitionPublish,
			"account/publish_account_transition_code_with_two"
		},
		{
			Type.TransitionDelete,
			"account/delete_account_transition_code_with_two"
		},
		{
			Type.CheckTimeSlipRotationPeriod,
			"check/check_time_slip_card_master_hash"
		}
	};
}
